### ISSUE TITLE
Question about this beautiful utility in c+ or Arduino *ino...

### ISSUE THREAD

**Issue by itProfi** [miek/milight#1]
Dear Miek! Have you code in C++ or Arduino _.ino files? I am not understand Python, but i very want use you  utility on esp8266 (_.ino files) to control MiLight with dual white with this repo - https://github.com/DirkHeinke/arduino-milight . Can you help me in this question?
Thank you!

**Comment by miek** [comment]
The code here is designed to be used with a software-defined radio peripheral, which is a very flexible radio system.

The radio ESP8266 can only do WiFi, so it's not compatible with the protocol used between the MiLight bulbs/remotes

**Comment by itProfi** [comment]
Friend! I want use esp8266 or Arduino, like i said, like in https://github.com/DirkHeinke/arduino-milight...(with nrf24l01) Can you write codes like in https://github.com/DirkHeinke/arduino-milight/blob/master/src/arduino-milight.cpp#L51 (I mean codes in new MilIght protocol, which you describe in you page) or only codes in binary format?

**Comment by miek** [comment]
The code here works with raw radio signals, it can't work on an ESP8266 or Arduino.

You could take some of the information from here and use it to modify the arduino-milight project to support dual-white bulbs.

Also check out https://github.com/pmoscetta/authometion-milight which apparently supports dual-white.

**Comment by itProfi** [comment]
Ok, thank you.
